services:
  root:
    restart: always
    build: 
      context: ./root
    
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27000:27017
  
  #  mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo
  #   environment:
  #     - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
  #     - "ME_CONFIG_MONGODB_ADMINPASSWORD=example"
  #     - "ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/"
  #     - "ME_CONFIG_BASICAUTH=false"
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 8080:80
    depends_on:
      - root
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf