FROM node:20 as baseImage
WORKDIR /App
COPY package*.json ./
RUN npm install
EXPOSE 5000
CMD ["npm", "start"]

FROM node:20 as build
WORKDIR /App
COPY . ./
RUN npm install
RUN npm run build



FROM node:20 as prod
WORKDIR /App
COPY package*.json ./
RUN npm install --only=production
COPY --from=build /App/dist ./dist
CMD ["npm", "start"]


FROM node:20 as dev
WORKDIR /App
COPY package*.json ./
RUN npm install
COPY ./ ./
CMD ["npm", "run","start:dev"]
